<?php

namespace ContainerXyho6P1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CoLo6dJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.coLo6dJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.coLo6dJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FactureController::delete' => ['privates', '.service_locator.njvUyPK', 'get_ServiceLocator_NjvUyPKService', true],
            'App\\Controller\\FactureController::edit' => ['privates', '.service_locator.njvUyPK', 'get_ServiceLocator_NjvUyPKService', true],
            'App\\Controller\\FactureController::index' => ['privates', '.service_locator.IpMxtu_', 'get_ServiceLocator_IpMxtuService', true],
            'App\\Controller\\FactureController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FactureController::show' => ['privates', '.service_locator.XVjfyza', 'get_ServiceLocator_XVjfyzaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FactureController:delete' => ['privates', '.service_locator.njvUyPK', 'get_ServiceLocator_NjvUyPKService', true],
            'App\\Controller\\FactureController:edit' => ['privates', '.service_locator.njvUyPK', 'get_ServiceLocator_NjvUyPKService', true],
            'App\\Controller\\FactureController:index' => ['privates', '.service_locator.IpMxtu_', 'get_ServiceLocator_IpMxtuService', true],
            'App\\Controller\\FactureController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\FactureController:show' => ['privates', '.service_locator.XVjfyza', 'get_ServiceLocator_XVjfyzaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FactureController::delete' => '?',
            'App\\Controller\\FactureController::edit' => '?',
            'App\\Controller\\FactureController::index' => '?',
            'App\\Controller\\FactureController::new' => '?',
            'App\\Controller\\FactureController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FactureController:delete' => '?',
            'App\\Controller\\FactureController:edit' => '?',
            'App\\Controller\\FactureController:index' => '?',
            'App\\Controller\\FactureController:new' => '?',
            'App\\Controller\\FactureController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
