# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    photo_dir: "%kernel.project_dir%/public/images"
    mercure_secret_key: '%env(MERCURE_SECRET_KEY)%' 
    app.jwtsecret: '%env(JWT_SECRET)%'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $stripeSK: "%env(STRIPE_SK)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Service\StripeService:
        arguments:
            $stripeApiKey: '%env(STRIPE_API_KEY)%'

    App\Repository\UserRepository:
        autowire: true
        autoconfigure: false
  
    App\Entity\User:
        autowire: true
        autoconfigure: false
    
    App\Repository\TypedechetsRepository:
        autowire: true
        autoconfigure: false
  
    App\Entity\Typedechets:
        autowire: true
        autoconfigure: false
    
    App\Controller\TypedechetsController:
        autowire: true
        autoconfigure: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
