<?php

namespace Container8iUnmAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IpMxtuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IpMxtu_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IpMxtu_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'factureRepository' => ['privates', 'App\\Repository\\factureRepository', 'getFactureRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'factureRepository' => 'App\\Repository\\factureRepository',
            'paginator' => '?',
        ]);
    }
}
