<?php

namespace Container8iUnmAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFacture2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.njvUyPK.App\Entity\Facture' shared service.
     *
     * @return \App\Entity\Facture
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.njvUyPK": it references class "App\\Entity\\Facture" but no such service exists.');
    }
}
