api_login_check:
    path: /api/login_check

app_verify_email:
    path: /verify
    controller: App\Controller\RegistrationController::verifyUserEmail 

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_user_home:
    path : /home
    controller: 'App\Controller\HomeController::indexHome'


app_user_contact:
    path : /user/contact
    controller: 'App\Controller\UserController::indexContact'


app_user_index:
    path: /admin/users
    controller: 'App\Controller\AdminController::index'   
    methods: ['GET']

app_user_forUser:
    path: /user/forUser
    controller: 'App\Controller\UserController::indexUser'

app_user_show:
    path: /admin/{id}
    controller: App\Controller\AdminController::show
    requirements:
        id: \d+  # Ensure the id parameter is a digit (integer)

app_check_email:
    path: /reset-password/check-email
    controller: App\Controller\ResetPasswordController::checkEmail
    methods: ['GET']

app_user_edit:
    path: /admin/{id}/edit
    controller: App\Controller\AdminController::edit
    methods: ['GET', 'POST']
    requirements:
        id: \d+  # Ensure the id parameter is a digit (integer)

app_user_delete:
    path: /admin/{id}
    controller: App\Controller\AdminController::delete
    methods: ['POST']
    requirements:
        id: \d+  # Ensure the id parameter is a digit (integer)

profile_edit:
    path: /user/profile/{id}/edit
    controller: App\Controller\UserController::editProfile
    methods: ['GET', 'POST']
    requirements: 
        id: \d+  # User ID


app_reset_password:
    path: '/reset-password/reset/{token}'
    controller: App\Controller\SecurityController::resetpassword
    methods: ['GET','POST']        
