app_admin_index:
    path: /admin
    controller: App\Controller\FactureController::indexAdmin
app_facture_new:
    path: '/facture/new'
    controller: App\Controller\FactureController::new
app_facture_index:
    path: '/facture/index'
    controller: App\Controller\FactureController::index