<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyho6P1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyho6P1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyho6P1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyho6P1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyho6P1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xyho6P1',
    'container.build_id' => '1f5beba0',
    'container.build_time' => 1712891677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyho6P1');
